
# SCOOP_ARIA2=1

TYPING_VIETNAMESE_LINK=https://github.com/lamquangminh/EVKey/releases/download/Release/EVKey.zip
AUTOSTART_WITH_WINDOWS=1

ENABLE_UTC_TIME=1
TIME_ZONE="SE Asia Standard Time"
FORMAT_TIME="H:mm"
FORMAT_DATE="dd/MM/yyyy"

ENABLE_SHOW_HIDDEN_FILES=1
ENABLE_SHOW_HIDDEN_EXTENSIONS=1
DISABLE_SHOW_HIDDEN_SHOW_RECENTLY_FILES=1
DISABLE_SHOW_HIDDEN_SHOW_FREQUENTLY_FILES=1
OPEN_EXPLORER_DEFAULT_WITH_THIS_PC=1

SET_DEFAULT_WSL2=1
ENABLE_HYPER_V=1
ENABLE_WSL=1
ENABLE_VIRTUAL_MACHINE=1
ENABLE_SANDBOX=1

INSTALL_NODEJS=1
NODEJS_VERSION=22
NODEJS_GLOBAL_PACKAGES="pnpm yarn"

# CLEAR_SETUP_TMP_DIR